# Generated by Django 4.2.7 on 2024-07-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kampuni', '0002_user_is_active_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='orgId',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='user_id',
        ),
    ]
